version: "3"

env:
  PATH: "{{.HOME}}/go/bin:{{.PATH}}"

vars:
  SPNDEX_DB_DSN: '{{.SPNDEX_DB_DSN | default ""}}'

tasks:
  help:
    desc: print this help message
    cmds:
      - task --list-all
    silent: true

  confirm:
    desc: confirmation prompt
    cmds:
      - |
        echo -n 'Are you sure? [y/N] ' && read ans && [ ${ans:-N} = y ]
    silent: true
    internal: true

  run:
    desc: run the cmd/spndex application
    cmds:
      - go run ./cmd/spndex/main.go

  migrations:new:
    desc: create a new database migration
    vars:
      NAME: '{{.name | default ""}}'
    cmds:
    - |
      if [ -z "{{.NAME}}" ]; then
        echo "Usage: task migrations:new name=migration_name"
        exit 1
      fi
    - echo 'Creating migration file for {{.NAME}}...'
    - tern new -m ./internal/database/migrations {{.NAME}}

  migrations:down:
    desc: rollback all database migrations to zero
    deps: [ confirm ]
    dotenv: [".env"]
    cmds:
      - echo 'Rolling back all migrations...'
      - tern migrate -m ./internal/database/migrations --conn-string "$TERN_DSN" --destination 0

  migrations:down:one:
    desc: rollback the single most recent migration
    deps: [ confirm ]
    dotenv: [".env"]
    cmds:
      - echo 'Rolling back one migration...'
      - tern migrate -m ./internal/database/migrations --conn-string "$TERN_DSN" --destination -1


  migrations:down:to:
    desc: rollback database migrations to a specific version (usage - task migrations:down:to version=1)
    deps: [ confirm ]
    dotenv: [".env"]
    vars:
      VERSION: '{{.version | default ""}}'
    cmds:
      - |
        if [ -z "{{.VERSION}}" ]; then
          echo "Usage: task migrations:down:to version=<number>"
          exit 1
        fi
      - echo 'Rolling back to version {{.VERSION}}...'
      - tern migrate -m ./internal/database/migrations --conn-string "$TERN_DSN" --destination {{.VERSION}}

  migrations:up:
    desc: apply all up database migrations
    deps: [ confirm ]
    dotenv: [".env"]
    cmds:
    - echo 'Running up migrations...'
    - tern migrate -m ./internal/database/migrations --conn-string "$TERN_DSN"

  tidy:
    desc: format all .go files, and tidy and vendor module dependencies
    cmds:
      - echo 'Formatting .go files...'
      - go fmt ./...
      - echo 'Tidying module dependencies...'
      - go mod tidy
      - echo 'Verifying dependencies...'
      - go mod verify
